version: "3.8"

services:
  jeanmora:
    image: jeanmora:latest
    build: .
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.jeanmora.entrypoints=http"
        - "traefik.http.routers.jeanmora.rule=Host(`jeanmora.byronrm.com`)"
        - "traefik.http.middlewares.jeanmora-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.jeanmora.middlewares=jeanmora-https-redirect"
        - "traefik.http.routers.jeanmora-secure.entrypoints=https"
        - "traefik.http.routers.jeanmora-secure.rule=Host(`jeanmora.byronrm.com`)"
        - "traefik.http.routers.jeanmora-secure.tls=true"
        - "traefik.http.routers.jeanmora-secure.tls.certresolver=http"
        - "traefik.http.routers.jeanmora-secure.service=jeanmora"
        - "traefik.http.services.jeanmora.loadbalancer.server.port=80"
        - "traefik.docker.network=traefik-public"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true